/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Ivana
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        logout.setVisible(false);
        tambahmobil.setVisible(false);
        peminjamanmobil.setVisible(false);
        tambahuser.setVisible(false);
        pengembalianmobil.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menudata = new javax.swing.JMenu();
        tambahmobil = new javax.swing.JMenuItem();
        tambahuser = new javax.swing.JMenuItem();
        menutransaksi = new javax.swing.JMenu();
        peminjamanmobil = new javax.swing.JMenuItem();
        pengembalianmobil = new javax.swing.JMenuItem();
        menuakun = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Rental Mobil");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APLIKASI RENTAL MOBIL");

        jLabel3.setBackground(new java.awt.Color(153, 255, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Oleh Ivan Avandi");

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1291, 1291, 1291)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1440, 1440, 1440)
                        .addComponent(jLabel3)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addContainerGap(750, Short.MAX_VALUE))
        );

        menudata.setText("Data");
        menudata.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tambahmobil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tambahmobil.setText("Tambah Mobil");
        tambahmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahmobilActionPerformed(evt);
            }
        });
        menudata.add(tambahmobil);

        tambahuser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tambahuser.setText("Tambah User");
        tambahuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahuserActionPerformed(evt);
            }
        });
        menudata.add(tambahuser);

        jMenuBar1.add(menudata);

        menutransaksi.setText("Transaksi");
        menutransaksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        peminjamanmobil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        peminjamanmobil.setText("Peminjaman Mobil");
        peminjamanmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanmobilActionPerformed(evt);
            }
        });
        menutransaksi.add(peminjamanmobil);

        pengembalianmobil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pengembalianmobil.setText("Pengembalian Mobil");
        pengembalianmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianmobilActionPerformed(evt);
            }
        });
        menutransaksi.add(pengembalianmobil);

        jMenuBar1.add(menutransaksi);

        menuakun.setText("Akun");
        menuakun.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        login.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        menuakun.add(login);

        logout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menuakun.add(logout);

        jMenuBar1.add(menuakun);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahmobilActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Mobil fm = new Mobil();
        fm.setVisible(true);
        jDesktopPane1.add(fm);         
    }//GEN-LAST:event_tambahmobilActionPerformed

    private void tambahuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahuserActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        User fm = new User();
        fm.setVisible(true);
        jDesktopPane1.add(fm);    
    }//GEN-LAST:event_tambahuserActionPerformed

    private void peminjamanmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanmobilActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Peminjaman fm = new Peminjaman();
        fm.setVisible(true);
        jDesktopPane1.add(fm);      
    }//GEN-LAST:event_peminjamanmobilActionPerformed

    private void pengembalianmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianmobilActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Pengembalian fm = new Pengembalian();
        fm.setVisible(true);
        jDesktopPane1.add(fm);      
    }//GEN-LAST:event_pengembalianmobilActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        login.setVisible(true);
        logout.setVisible(false);
        logout.setVisible(false);
        tambahmobil.setVisible(false);
        peminjamanmobil.setVisible(false);
        tambahuser.setVisible(false);
        pengembalianmobil.setVisible(false);       
    }//GEN-LAST:event_logoutActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        dispose();
        Login fm = new Login();
        fm.setVisible(true);        
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    public void admin() {

        tambahmobil.setVisible(true);
        peminjamanmobil.setVisible(true);
        tambahuser.setVisible(true);
        logout.setVisible(true);
        login.setVisible(false);
        pengembalianmobil.setVisible(true);
    }

    public void user() {
        tambahmobil.setVisible(true);
        peminjamanmobil.setVisible(true);
        tambahuser.setVisible(false);
        logout.setVisible(true);
        login.setVisible(false);
        pengembalianmobil.setVisible(true);    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem login;
    public static javax.swing.JMenuItem logout;
    public static javax.swing.JMenu menuakun;
    public static javax.swing.JMenu menudata;
    public static javax.swing.JMenu menutransaksi;
    public static javax.swing.JMenuItem peminjamanmobil;
    public static javax.swing.JMenuItem pengembalianmobil;
    public static javax.swing.JMenuItem tambahmobil;
    public static javax.swing.JMenuItem tambahuser;
    // End of variables declaration//GEN-END:variables
}
